### ISSUE TITLE
Circulation with resetting the password

### ISSUE THREAD

**Issue by LBeckX** [terminal42/contao-password-validation#16]
If the Contao user needs to change his password, the password form is displayed. After successfully changing the password, the user will be redirected to the login. If the user enters his new data there, he gets the message that he has to change his password again.
So the user can never log in.

- Contao: 4.9
- PHP: 7.3

`config.yml`
```yml
terminal42_password_validation:
    Contao\FrontendUser:
    Contao\BackendUser:
        min_length: 10
        change_days: 180
        require:
            uppercase: 1
            lowercase: 1
            numbers: 1
            other: 1
```
