### ISSUE TITLE
Password validation inactive in BackendPassword controller

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-password-validation#3]
If you create/edit a new back end user and enable the `pwChange` option for a user, the password change procedure will not enforce the defined password validation rules. But what's even worse: somehow, the password that is entered will not be able to validate and thus the user cannot log in at all.

Tested in Contao `4.8.7`.

### Reproduction

Example configuration:

```yml
# config/config.yml
terminal42_password_validation:
  Contao\BackendUser:
    min_length: 10
    require:
      uppercase: 1
      lowercase: 1
      numbers: 1
    password_history: 2
```

1. Edit your own back end user.
2. Enable the `pwChange` option.
3. Save - you will be automatically logged out by Contao and shown the forced password change form.
4. Enter the following password two times: `123456789`.
5. Click _Next_.

Even though the password does not fit the validation rules, Contao reports that the password has been changed successfully.

6. Put in your user name and the newly set password `123456789`.
7. Click _Login_.

You will not be able to log in with the previously, newly set password.

**Comment by fritzmg** [comment]
Interestingly https://github.com/eikona-media/contao-password-policy seems to have the same second problem (the newly set password not being valid upon the next login). May be that's somehow a core bug?

**Comment by richardhj** [comment]
We have multiple problems with the `BackendPassword` controller:
- The `BackendPassword` controller does not check for the rgxp, while we use the `terminal42_password_validation` rgxp to validate the password. This can be fixed by calling the rgxp hook in the `BackendPassword` controller.
- The `BackendPassword` controller does not catch Exceptions, thus validation errors (that are thrown as exception via save_callback/rgxp) do not get caught.

IMHO the best approach to fix this is to rewrite the `BackendPassword` controller to use `$objWidget = new Password();`, and use `$objWidget->validate()` with the default validation rules the `Widget` class comes with.
WDYT @aschempp ?

**Comment by aschempp** [comment]
Sounds reasonable to me. Maybe this is something that can be fixed in Contao core?

**Comment by aschempp** [comment]
@richardhj can you take care of a solution for this?

**Comment by zonky2** [comment]
> **A:** If you create/edit a new back end user and enable the pwChange option for a user, the password change procedure will not enforce the defined password validation rules.
> **B:** But what's even worse: somehow, the password that is entered will not be able to validate and thus the user cannot log in at all.

B: is fixed, THX!

A: the bug still exists

```
terminal42_password_validation:
  Contao\FrontendUser:
    min_length: 8
    require:
      numbers: 1
      other: 1
    other_chars: "+-=%?!§&()@,._#/"
  Contao\BackendUser:
    min_length: 8
    require:
      numbers: 1
      other: 1
    other_chars: "+-=%?!§&()@,._#/"
```

If I set PW in backend with TTtester20201 - I get an error message to adjust the password...
I set to TT-tester+2020-1 and checkbox to change PW at first login - I can now assign TTtester20201 as new PW without an error  message :(
