### ISSUE TITLE
Password rules are not used during registration process (feature request)

### ISSUE THREAD

**Issue by markusmilkereit** [terminal42/contao-password-validation#8]
I installed and set up the extension, and everything regarding passwords works magically in the backend. What I could not see, but it would be a major component for my: validating the password during registration.

If I did something wrong please point me in the right direction :)

**Comment by aschempp** [comment]
maybe @richardhj can point this out? Not sure if that's even supported (yet)?

**Comment by richardhj** [comment]
Hm, we are using the `addCustomRegexp` hook and the ModuleRegistration.php triggers the rgxp check (on $objWidget->validate()), so it is supposed to work.

**Comment by markusmilkereit** [comment]
In `PasswordRegexpListener::addCustomRegexp` you're jumping out if there is no DC table set - which it's not during registration, there is no table attached yet (only after successful registration, when a member was created).

So I just did a quick hack to enable the regex during registration in lines 56ff:
```PHP
} else {
       // return true;
      $userId = 0;
      $userEntity = FrontendUser::class;
}
```

And you should update the documentation, or the error messages will be very confusing - contao checks it's own min_length rule first, so usually it's a different number (and a misleading error message then): 

```YML
contao:
    localconfig:
        minPasswordLength: <set same length as>
        
terminal42_password_validation:
    Contao\FrontendUser:
        min_length: 10
```

With those changes it works really nicely also for the registration process.
